---

- name: Automated vm maintenance
  hosts: all 
  become: true
  become_method: sudo

  tasks:
            
   - name: apt update
     shell: sudo apt update
     register:  update_output
     retries: 1
     delay: 10
     until: update_output.rc == 0

   - name: Show update output
     debug:
       var: update_output

   - name: apt ckeck list
     shell: apt list --upgradable
     register:  update_output
     retries: 1
     delay: 10
     until: update_output.rc == 0
     register: output_list

   - name: show list output
     debug:
       var: output_list 

         
   - name: Reboot system if update successful
     shell: init 6
     async: 1
     poll: 0
     when: update_output.rc == 0
